import { LocationEnum, Vehicle, VehicleStatus } from './types';

// ==================================================================================
// CONFIGURAÇÃO DO BANCO DE DADOS (SUPABASE)
// Para salvar em vários dispositivos, crie um projeto em https://supabase.com
// e cole a URL e a API Key (anon public) abaixo.
// ==================================================================================
export const SUPABASE_CONFIG = {
  url: 'https://rxhvdyxftgjzieaieurt.supabase.co', // Ex: https://xyz.supabase.co
  key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aHZkeXhmdGdqemllYWlldXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Mjk3ODUsImV4cCI6MjA3OTQwNTc4NX0.zPlXIXG64BkENfq-34t1MKtPzqZyMTIWH11GJQeeexE', // Ex: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
};

export const AVAILABLE_LOCATIONS = [
  LocationEnum.PAT,
  LocationEnum.ETC_5,
  LocationEnum.ETC_6,
  LocationEnum.ETC_7,
  LocationEnum.ECL_3,
  LocationEnum.ECL_4,
  LocationEnum.PIT,
  LocationEnum.PTI,
  LocationEnum.RAMAL_5,
  LocationEnum.RAMAL_6,
  LocationEnum.OFICINA,
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'TM 01',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-001',
  },
  {
    id: 'TM 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-002',
  },
  {
    id: 'TM 05',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-003',
  },
  {
    id: 'TM 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-006',
  },
  {
    id: 'TM 11',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-004',
  },
  {
    id: 'TM 15',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-005',
  },
  {
    id: 'TM 16',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-018',
  },
  {
    id: 'TM 17',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-019',
  },
  {
    id: 'TV 209',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-007',
  },
  {
    id: 'TV 212',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-008',
  },
  {
    id: 'TV 220',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-020',
  },
  {
    id: 'TV 223',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-009',
  },
  {
    id: 'TV 222',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-010',
  },
  {
    id: 'ME 12',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-011',
  },
  {
    id: 'ME 13',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-012',
  },
  {
    id: 'VF 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-013',
  },
  {
    id: 'VF 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-014',
  },
  {
    id: 'VF 06',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-015',
  },
  {
    id: 'ME 10',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-016',
  },
  {
    id: 'ME 09',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-017',
  },
  {
    id: 'ME 15',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-021',
  },
];