import { LocationEnum, Vehicle, VehicleStatus } from './types';

export const AVAILABLE_LOCATIONS = [
  LocationEnum.PAT,
  LocationEnum.ETC_5,
  LocationEnum.ETC_7,
  LocationEnum.ECL_3,
  LocationEnum.ECL_4,
  LocationEnum.PIT,
  LocationEnum.RAMAL_5,
  LocationEnum.RAMAL_6,
  LocationEnum.OFICINA,
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'TM 01',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-001',
  },
  {
    id: 'TM 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-002',
  },
  {
    id: 'TM 05',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-003',
  },
  {
    id: 'TM 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-006',
  },
  {
    id: 'TM 11',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-004',
  },
  {
    id: 'TM 15',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-005',
  },
  {
    id: 'TV 209',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-007',
  },
  {
    id: 'TV 212',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-008',
  },
  {
    id: 'TV 223',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-009',
  },
  {
    id: 'TV 222',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-010',
  },
  {
    id: 'ME 12',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-011',
  },
  {
    id: 'ME 13',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-012',
  },
  {
    id: 'VF 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-013',
  },
  {
    id: 'VF 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-014',
  },
  {
    id: 'VF 06',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-015',
  },
  {
    id: 'ME 10',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-016',
  },
  {
    id: 'ME 09',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-017',
  },
];