

import { LocationEnum, Vehicle, VehicleStatus } from './types';

// =================================================================
// CONFIGURAÇÃO DE BANCO DE DADOS (SUPABASE)
// Para salvar em outros dispositivos, crie um projeto em supabase.com
// e cole suas chaves aqui.
// =================================================================
export const SUPABASE_URL = "https://rxhvdyxftgjzieaieurt.supabase.co"; // Ex: "https://xyz.supabase.co"
export const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aHZkeXhmdGdqemllYWlldXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Mjk3ODUsImV4cCI6MjA3OTQwNTc4NX0.zPlXIXG64BkENfq-34t1MKtPzqZyMTIWH11GJQeeexE"; // Ex: "eyJhbGciOiJIUzI1NiIsInR5..."

export const AVAILABLE_LOCATIONS = [
  LocationEnum.PAT,
  LocationEnum.RAMAL_5,
  LocationEnum.RAMAL_6,
  LocationEnum.ETC_5,
  LocationEnum.ETC_6,
  LocationEnum.ETC_7,
  LocationEnum.TM_02_ANR,
  LocationEnum.TM_02_LUZ,
  LocationEnum.PTI,
  LocationEnum.ECL_3,
  LocationEnum.ECL_4,
  LocationEnum.PIT,
  LocationEnum.EPB_1,
  LocationEnum.EPB_2,
  LocationEnum.OFICINA,

];

// Registry of Operators and their Registration IDs
export const OPERATOR_REGISTRY: { [key: string]: string } = {
    'Waldemir Angelo Martins': '9101-8',
    'Neimar Mufalo': '14477-4',
    'Antonio Carlos Ribeiro': '18164-5',
    'Luiz Fernando de Souza Arruda': '18484-9',
    'Edivaldo Cordeiro Silva': '19178-1',
    'Osorio Sant Anna Neto': '19182-9',
    'Luiz Claudio dos Santos': '19323-6',
    'William Aldo Teodoro': '19745-2',
    'Luciano Cremonese': '19885-8',
    'Julio Cesar Martins': '20513-7',
    'Fabiano Jose dos Santos': '20766-1',
    'Alencar Marcos de Negri': '20828-4',
    'Josemir Ananias da Silva': '20831-4',
    'Adilson Mendes Damascena': '20910-8',
    'Paulo Jose Furtado': '20957-4',
    'Joao Batista de Araujo': '20961-2',
    'Ivair Ribeiro': '21039-4',
    'Marcio de Jesus Dias': '21040-8',
    'Uilton Antonio de Souza': '21365-2',
    'Carlos Alberto Pereira de Vasconcelos Junior': '21649-0',
    'Sergio Goncalves dos Reis': '21670-8',
    'Fabio Danilo Tolentino': '21786-1',
    'Claudney de Almeida Franco': '21822-1',
    'Luiz Fernando da Silva Domingos': '21825-5',
    'Ricardo Gomes': '22019-5',
    'David Pinto de Oliveira': '22021-7',
    'Jean Carlos Martins dos Santos': '22026-8',
    'Elias Marcos Machado Nemet': '22075-6',
    'Jose Carlos Rios': '22078-1',
    'Luciano Severino da Silva': '22104-3',
    'Osley de Souza Silva': '22117-5',
    'Luiz Antonio Vergilio': '22121-3',
    'Ricardo dos Reis': '22122-1',
    'Alberto Zuchiwschi': '22123-0',
    'Jackson Lima de Mendonca': '22126-4',
    'Helio Ribeiro Avelino de Oliveira': '22161-2',
    'Andre Nunes Lima': '22171-0',
    'Glaucio Ferreira': '22194-9',
    'Carlos Henrique Heilig Sao Severino': '22195-7',
    'Abilio Cardoso dos Santos': '22201-5',
    'Cassiano Ricardo Ferreira de Souza': '22203-1',
    'Carlos Teijido Veira': '22222-8',
    'Leandro Lopes Gomes': '22258-9',
    'Roberto Claudio Luciano': '22259-7',
    'Valdir Felipe dos Santos': '22265-1',
    'Vanilton Pires Viana': '22271-6',
    'Luciano Vieira de Oliveira': '22327-5',
    'Luiz Ferreira': '22357-7',
    'Silvio Villarrazo Junior': '22799-8',
    'Edis Alves de Brito': '22845-5',
    'Ricardo Jose de Oliveira': '22894-3',
    'Cristiano Pereira dos Santos': '22912-5',
    'Wellington de Menezes Santos': '22942-7',
    'Luiz Carlos Moraes Marques': '22951-6',
    'Valdomiro Aparecido Antonio Caetano': '23063-8',
    'Geanderson Nascimento dos Santos': '23167-7',
    'Hernandes da Fonseca Cavalcante': '23200-2',
    'Eduardo Siqueira Junior': '23245-2',
    'Leonardo Ribeiro': '23247-9',
    'Allan Nascimento Romualdo Paixao': '23255-0',
    'Fabio de Vechi': '23858-2',
    'Tiago Vico da Silva': '23876-1',
    'Otniel Moraes de Oliveira': '23902-3',
    'Eduardo Estevao da Silva': '23920-1',
    'Erick Emanoel Sampaio': '23976-7',
    'Cicero Ribeiro Lustoza': '24008-1',
    'Thiago Luiz das Neves': '24026-9',
    'Antonio Pereira da Silva': '24036-6',
    'Jorge Augusto Santos Ribeiro': '24077-3',
    'José Edson de Souza': '24081-1',
    'Rogerio de Sousa Henriques': '24417-5',
    'Antonio Mourao Junior': '24486-8',
    'Luiz Ricardo Mendes': '24588-1',
    'Joselito Santiago Borges': '24590-2',
    'Samuel Miguel de Oliveira': '24998-3',
    'Neomar Santana Garcia': '25002-7',
    'Daniel Augusto Cabral': '25003-5',
    'Fabricio Vicente da Silva': '25260-7',
    'Douglas Viesel': '25265-8',
    'Caio Vinicius Graça dos Santos': '25276-3',
    'Fabio Oliveira de Lima': '26993-3',
    'Danilo Dias de Mello': '27024-9',
    'Ramon Quintino Bastos': '28893-8',
    'Douglas Azevedo de Oliveira': '29048-7',
    'Paulo Martins da Silva Junior': '29521-7',
    'Willian Nunes Rocha Fonseca': '29728-7',
    'Caique Augusto Dos Santos': '31424-6',
    'Adriano Ferreira Nunes Santos': '32522-1',
    'Wanderley Neri Cedraz': '32918-9',
    'Almir Rogério Cyrino': '32919-7',
    'Valdir Tadeu Candido': '16075-3',
    'Ricardo Inicencio da Silva Muta': '33851-0',
    'Manoel Antonio Roque': '13891-0',
    'David Xavier de Brito Costa': '24601-1'
};

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'TM 01',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-001',
  },
  {
    id: 'TM 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-002',
  },
  {
    id: 'TM 05',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-003',
  },
  {
    id: 'TM 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-006',
  },
  {
    id: 'TM 11',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-004',
  },
  {
    id: 'TM 15',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-005',
  },
  {
    id: 'TM 16',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-018',
  },
  {
    id: 'TM 17',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-019',
  },
  {
    id: 'TV 209',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-007',
  },
  {
    id: 'TV 212',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-008',
  },
  {
    id: 'TV 220',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-020',
  },
  {
    id: 'TV 223',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-009',
  },
  {
    id: 'TV 222',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-010',
  },
  {
    id: 'ME 13',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-012',
  },
  {
    id: 'VF 03',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-013',
  },
  {
    id: 'VF 07',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-014',
  },
  {
    id: 'VF 06',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-015',
  },
  {
    id: 'ME 10',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-016',
  },
  {
    id: 'ME 15',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-021',
  },
  {
    id: 'TV 207',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-022',
  },
  {
    id: 'TV 215',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-023',
  },
  {
    id: 'TV 218',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-024',
  },
  {
    id: 'TV 217',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-025',
  },
  {
    id: 'TV 277',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-026',
  },
  {
    id: 'VF 01',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-027',
  },
  {
    id: 'VF 04',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-028',
  },
  {
    id: 'TM 09',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-029',
  },
  {
    id: 'VF 11',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-030',
  },
  {
    id: 'VF 10',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-031',
  },
  {
    id: 'TV 219',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-032',
  },
  {
    id: 'TV 203',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-033',
  },
  {
    id: 'TV 273',
    lastLocation: null,
    currentLocation: LocationEnum.PAT,
    operator: 'Sistema',
    lastUpdate: new Date().toISOString(),
    status: VehicleStatus.OPERATION,
    registration: 'REG-034',
  },
];